name: photo_puzzle
description: A mobile photo puzzle game built with Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#070B3E"
  image: assets/icon/splash_logo.png
  android_12:
    image: assets/icon/splash_logo.png
    color: "#070B3E"
  android: true
  ios: false
